server:
  port: 8081

# DB configs
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/springsecurity?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
    username: 'root'
    password: 'secret'
    initialization-mode: always

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = LOGGING
# ===============================
logging:
  level:
    io.javabrains: debug
    org.hibernate.SQL: info